### ISSUE TITLE
unable to find the exporter

### ISSUE THREAD

**Issue by doradoro** [Aetheris743/Blender-PBR-Texture-Exporter#4]
I'm having trouble to find that "Export Objects" button. There is nothing in the File / Export menu and either inside fbx or gltf exporters... how can i use it?

**Comment by Aetheris743** [comment]
The menu for exporting the textures is right below the cycles "Bake" menu in the render settings (on my computer). 
![image](https://user-images.githubusercontent.com/45411688/129601317-07a4776a-481a-4fb2-8878-b7b878f9e592.png)

In a future version I might add a toggle to the FBX and glTF exporters to also export the textures.

**Comment by doradoro** [comment]
Thanks!
