### ISSUE TITLE
Explain where to find the export panel

### ISSUE THREAD

**Issue by Jefficus** [Aetheris743/Blender-PBR-Texture-Exporter#6]
I naively assumed that the export panel referred to in the instructions meant the options panel of the File->Export->FBX operation. It never occurred to me to look in the Render Options for a panel of that name. I suggest wording along the lines of: Select the objects to export and the textures to export with them in the _newly created Export Panel section of the Render Properties panel._

**Comment by Aetheris743** [comment]
Documentation updated. Thanks for pointing that out!
